interface codingStyleObject {
    description: string;
    content: string;
}

export const codingStyles: codingStyleObject[] = [
  {
    "description": "level-1: only removing unnecessary spaces and new lines",
    "content": "This is the AI Coding Style Guide. Please follow the AI Coding Style Guide to finish tasks, including completing code snippets, refactoring, autocompleting, unit testing and more.\n\n1. Please try to remove unnecessary spaces and new lines. If the indention takes more than one spaces, please use one space only. Here is an example:\n\nWrong:\n```cpp\nint main() {\n\n    int a = 1;\n    int b = 2;\n    int c = a + b;\n\n    std::cout << c << std::endl;\n}\n```\n\nRight:\n```cpp\nint main(){\n int a=1;\n int b=2;\n int c=a+b;\n std::cout<<c<<std::endl;\n}\n```\n2. Please keep the comments of the code. Do not remove the comments.\n"
  },
  {
    "description": "level-2: removing unnecessary spaces and new lines, and slightly compressing the code",
    "content": "This is the AI Coding Style Guide. Please follow the AI Coding Style Guide to finish tasks, including completing code snippets, refactoring, autocompleting, unit testing and more.\n\n1. Please try to remove unnecessary spaces and new lines. If the indention takes more than one spaces, please use one space only. Here is an example:\n\nWrong:\n```cpp\nint main() {\n\n    int a = 1;\n    int b = 2;\n    int c = a + b;\n\n    std::cout << c << std::endl;\n}\n```\n\nRight:\n```cpp\nint main(){\n int a=1;\n int b=2;\n int c=a+b;\n std::cout<<c<<std::endl;\n}\n```\n\n2. Please keep the comments of the code. Do not remove the comments.\n\n3. Try to merge some lines of code together to make the code more compact, but do not change the logic of the code. Here is an example:\n```cpp\nint main(){\n\n int a = 1;\n int b = 2;\n int c = a + b;\n\n std::cout << c << std::endl;\n}\n``` \nYou can compress the code to:\n```cpp\nint main(){\n int a=1,b=2,c=a+b;\n std::cout<<c<<std::endl;\n}\n```\n\n"
  },
  {
    "description": "level-3: removing unnecessary spaces and new lines, slightly compressing the code, and making local variables shorter",
    "content": "This is the AI Coding Style Guide. Please follow the AI Coding Style Guide to finish tasks, including completing code snippets, refactoring, autocompleting, unit testing and more.\n\n1. Please try to remove unnecessary spaces and new lines. If the indention takes more than one spaces, please use one space only. Here is an example:\n\nWrong:\n```cpp\nint main() {\n\n    int a = 1;\n    int b = 2;\n    int c = a + b;\n\n    std::cout << c << std::endl;\n}\n```\n\nRight:\n```cpp\nint main(){\n int a=1;\n int b=2;\n int c=a+b;\n std::cout<<c<<std::endl;\n}\n```\n\n2. Please keep the comments of the code. Do not remove the comments.\n\n3. Try to merge some lines of code together to make the code more compact, but do not change the logic of the code. Here is an example:\n```cpp\nint main(){\n\n int a = 1;\n int b = 2;\n int c = a + b;\n\n std::cout << c << std::endl;\n}\n``` \nYou can compress the code to:\n```cpp\nint main(){\n int a=1,b=2,c=a+b;\n std::cout<<c<<std::endl;\n}\n```\n\n4. Try to make local variables shorter, but do not change the logic of the code. Here is an example:\n```cpp\nint main(){\n  int index = 0;\n  int sum = 0;\n  for(int i = 0; i < 10; i++){\n    sum += i;\n    index++;  \n  }\n}\n```\nYou can change the code to:\n```cpp\nint main(){\n int i=0,s=0;\n for(int j=0;j<10;j++){\n  s+=j;\n  i++;\n }\n}\n```\n"
  },
  {
    "description": "level-4: removing unnecessary spaces and new lines, slightly compressing the code, making local variables and non-exported functions, classes and variables shorter",
    "content": "This is the AI Coding Style Guide. Please follow the AI Coding Style Guide to finish tasks, including completing code snippets, refactoring, autocompleting, unit testing and more.\n\n1. Please try to remove unnecessary spaces and new lines. If the indention takes more than one spaces, please use one space only.\n2. Please keep the comments of the code. Do not remove the comments.\n3. Try to merge some lines of code together to make the code more compact, but do not change the logic of the code.\n4. Try to make local variables shorter, but do not change the logic of the code. \n\nHere is an example:\nWrong:\n```cpp\nint main(){\n  int index = 0;\n  int sum = 0;\n  for(int i = 0; i < 10; i++){\n    sum += i;\n    index++;  \n  }\n}\n```\nYou can change the code to:\n```cpp\nint main(){\n int i=0,s=0;\n for(int j=0;j<10;j++){\n  s+=j;\n  i++;\n }\n}\n```\n\n5. Try to make non-exported functions, classes and variables shorter, but do not change the logic of the code. And the exported functions, classes and variables should not be changed.\n\nHere is an example:\n```js\n// Helper function to square a number\nfunction squareNumber(num) {\n  return num * num;\n}\n\n// Helper function to check if a number is even\nfunction isEven(num) {\n  return num % 2 === 0;\n}\n\n// Exported function to calculate the sum of squares of even numbers up to n\nexport function sumOfEvenSquares(n) {\n  let sum = 0;\n  for (let i = 1; i <= n; i++) {\n    if (isEven(i)) {\n      sum += squareNumber(i);\n    }\n  }\n  return sum;\n}\n\n// Exported function to print the result\nexport function printSum(n) {\n  const result = sumOfEvenSquares(n);\n  console.log(\"Sum of even squares up to\", n, \"is\", result);\n}\n```\n\nAnd you need to change the code to:\n```js\n// Helper function to square a number\nfunction sq(n){return n*n;}\n// Helper function to check if a number is even\nfunction ev(n){return n%2==0;}\n// Exported function to calculate the sum of squares of even numbers up to n\nexport function sumOfEvenSquares(n){\n let s=0;\n for(let i=1;i<=n;i++)if(ev(i))s+=sq(i);\n return s;\n}\n// Exported function to print the result\nexport function printSum(n){\n const r=sumOfEvenSquares(n);\n console.log(\"Sum of even squares up to\",n,\"is\",r);\n}\n```\n"
  },
  {
    "description": "level-5: removing all whitespace, new lines, making local variables and non-exported functions, classes and variables shorter",
    "content": "This is the AI Coding Style Guide. Please follow the AI Coding Style Guide to finish tasks, including completing code snippets, refactoring, autocompleting, unit testing and more.\n\n1. Please try to remove all spaces, new lines and indentions.\n2. Please keep the comments of the code. Do not remove the comments.\n3. Try to merge some lines of code together to make the code more compact, but do not change the logic of the code.\n4. Try to make local variables shorter, but do not change the logic of the code. \n5. Try to make non-exported functions, classes and variables shorter, but do not change the logic of the code. And the exported functions, classes and variables should not be changed.\n\nHere is an example:\n```js\n// Helper function to square a number\nfunction squareNumber(num) {\n  return num * num;\n}\n\n// Helper function to check if a number is even\nfunction isEven(num) {\n  return num % 2 === 0;\n}\n\n// Exported function to calculate the sum of squares of even numbers up to n\nexport function sumOfEvenSquares(n) {\n  let sum = 0;\n  for (let i = 1; i <= n; i++) {\n    if (isEven(i)) {\n      sum += squareNumber(i);\n    }\n  }\n  return sum;\n}\n\n// Exported function to print the result\nexport function printSum(n) {\n  const result = sumOfEvenSquares(n);\n  console.log(\"Sum of even squares up to\", n, \"is\", result);\n}\n```\n\nAnd you need to change the code to:\n```js\n//Helper function to square a number\nfunction sq(n){return n*n;}\n//Helper function to check if a number is even\nfunction ev(n){return n%2==0;}\n//Exported function to calculate the sum of squares of even numbers up to n\nexport function sumOfEvenSquares(n){let s=0;for(let i=1;i<=n;i++)if(ev(i))s+=sq(i);return s;}\n//Exported function to print the result\nexport function printSum(n){const r=sumOfEvenSquares(n);console.log(\"Sum of even squares up to\",n,\"is\",r);}\n```\n"
  },
  {
    "description": "level-6: removing all whitespace, new lines, making local variables and non-exported functions, classes and variables shorter, and removing all comments except for the exported functions, classes and variables",
    "content": "This is the AI Coding Style Guide. Please follow the AI Coding Style Guide to finish tasks, including completing code snippets, refactoring, autocompleting, unit testing and more.\n\n1. Please try to remove all spaces, new lines and indentions.\n2. Please only keep the comments of the exported functions, classes and variables, and remove all other comments. If the comments of the exported functions, classes and variables are not necessary, you can also remove them or compress them.\n3. Try to merge some lines of code together to make the code more compact, but do not change the logic of the code.\n4. Try to make local variables shorter, but do not change the logic of the code. \n5. Try to make non-exported functions, classes and variables shorter, but do not change the logic of the code. And the exported functions, classes and variables should not be changed.\n\nHere is an example:\n```js\n// Helper function to square a number\nfunction squareNumber(num) {\n  return num * num;\n}\n\n// Helper function to check if a number is even\nfunction isEven(num) {\n  return num % 2 === 0;\n}\n\n// Exported function to calculate the sum of squares of even numbers up to n\nexport function sumOfEvenSquares(n) {\n  let sum = 0;\n  for (let i = 1; i <= n; i++) {\n    if (isEven(i)) {\n      sum += squareNumber(i);\n    }\n  }\n  return sum;\n}\n\n// Exported function to print the result\nexport function printSum(n) {\n  const result = sumOfEvenSquares(n);\n  console.log(\"Sum of even squares up to\", n, \"is\", result);\n}\n```\n\nAnd you need to change the code to:\n```js\nfunction sq(n){return n*n;}\nfunction ev(n){return n%2==0;}\n//sum of squares of even numbers up to n\nexport function sumOfEvenSquares(n){let s=0;for(let i=1;i<=n;i++)if(ev(i))s+=sq(i);return s;}\n//print the sum of even squares\nexport function printSum(n){const r=sumOfEvenSquares(n);console.log(\"Sum of even squares up to\",n,\"is\",r);}\n```\n"
  },
  {
    "description": "level-7: removing all whitespace, new lines, making local variables and non-exported functions, classes and variables shorter, and removing all comments",
    "content": "This is the AI Coding Style Guide. Please follow the AI Coding Style Guide to finish tasks, including completing code snippets, refactoring, autocompleting, unit testing and more.\n\n1. Please try to remove all spaces, new lines and indentions.\n2. Please do not keep any comments. Just remove all comments.\n3. Try to merge some lines of code together to make the code more compact, but do not change the logic of the code.\n4. Try to make local variables shorter, but do not change the logic of the code. \n5. Try to make non-exported functions, classes and variables shorter, but do not change the logic of the code. And the exported functions, classes and variables should not be changed.\n\nHere is an example:\n```js\n// Helper function to square a number\nfunction squareNumber(num) {\n  return num * num;\n}\n\n// Helper function to check if a number is even\nfunction isEven(num) {\n  return num % 2 === 0;\n}\n\n// Exported function to calculate the sum of squares of even numbers up to n\nexport function sumOfEvenSquares(n) {\n  let sum = 0;\n  for (let i = 1; i <= n; i++) {\n    if (isEven(i)) {\n      sum += squareNumber(i);\n    }\n  }\n  return sum;\n}\n\n// Exported function to print the result\nexport function printSum(n) {\n  const result = sumOfEvenSquares(n);\n  console.log(\"Sum of even squares up to\", n, \"is\", result);\n}\n```\n\nAnd you need to change the code to:\n```js\nfunction sq(n){return n*n;}\nfunction ev(n){return n%2==0;}\nexport function sumOfEvenSquares(n){let s=0;for(let i=1;i<=n;i++)if(ev(i))s+=sq(i);return s;}\nexport function printSum(n){const r=sumOfEvenSquares(n);console.log(\"Sum of even squares up to\",n,\"is\",r);}\n```\n"
  },
  {
    "description": "level-8: use any programming language features to make the code as short as possible, while keeping the functionality the same",
    "content": "This is the AI Coding Style Guide. Please follow the AI Coding Style Guide to finish tasks, including completing code snippets, refactoring, autocompleting, unit testing and more.\n\n1. Please do not keep any comments. Just remove all comments. Also do not keep any whitespace, new lines and indentions.\n2. Please try to use any programming language features to make the code as short as possible, while keeping the functionality the same.\n3. You can use any programming language features, such as lambda functions, list comprehensions, etc., to make the code as short as possible.\n4. You can do any code refactoring, such as using built-in functions, libraries, etc., to make the code as short as possible.\n5. Please keep the name of the exported functions, classes and variables the same, but you can change the name of the non-exported variables, functions, classes, member variables and member functions to make them shorter.\n"
  }
];
